name: pkg.pr.new
on:
    pull_request:
    push:
        branches:
            - "**"
        tags:
            - "!**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install
            - run: bunx pkg-pr-new publish
